spring.application.name=IPD-Management

# -----------------------
# IPD (Primary)
# ----------------------- Local DB Configuration for IPD 
#spring.datasource.ipd.jdbc-url=jdbc:mysql://localhost:3306/ipd_db
#spring.datasource.ipd.username=root
#spring.datasource.ipd.password=root
#spring.datasource.ipd.driver-class-name=com.mysql.cj.jdbc.Driver

# ----------------------- Live DB configuration for IPD
spring.datasource.ipd.jdbc-url=jdbc:mysql://localhost:3306/ipd_db
spring.datasource.ipd.username=hospiat_user
spring.datasource.ipd.password=123@Hospital
spring.datasource.ipd.driver-class-name=com.mysql.cj.jdbc.Driver

# -----------------------
# User Management (Secondary)
# ----------------------- Local DB Configuration for User Management
#spring.datasource.user.jdbc-url=jdbc:mysql://localhost:3306/user_management
#spring.datasource.user.username=root
#spring.datasource.user.password=root
#spring.datasource.user.driver-class-name=com.mysql.cj.jdbc.Driver

# ----------------------- Live DB Configuration for User Management
spring.datasource.user.jdbc-url=jdbc:mysql://localhost:3306/user_management
spring.datasource.user.username=hospiat_user
spring.datasource.user.password=123@Hospital
spring.datasource.user.driver-class-name=com.mysql.cj.jdbc.Driver

# -----------------------
# JPA Common
# -----------------------
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=8d#P@f92$Lm!vRzXq1TgB7nKw3uYc^H0zE4rS*J9o

server.port=3003

#billing.base.url=http://147.93.28.8:3005/api/billing/
billing.base.url=http://localhost:3005/api/billing/


#Will use in the IPD service caller controller
#billing.base.ipd.url=http://localhost:3005/api/ipd/billing/

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=30MB